```{r, setting-options, echo=FALSE}

Note_option <- ifelse(input$comments == "", FALSE, TRUE)

```


# Stand Density Management Diagram Report

* Date/time: `r format(Sys.time(), "%b %d, %X, %Y")`


## Stand Description

```{r, Stand-Description, echo=FALSE}

SP_REF <- switch(as.numeric(input$ineq), 
                "User Defined",                                      #1
                "Ponderosa Pine (Long and Shaw 2005)",               #2
                "Ponderosa Pine (Jang et al. 2021)",                 #3
                "Ponderosa Pine (Edminster 1988)",                   #4
                "Ponderosa Pine (Cochran 1992)",                     #5
                "Mixed-Conifer (Long and Shaw 2012)",                #6
                "Coastal Douglas-Fir (Long et al. 1988)",            #7
                "White Fir (Zhang et al. 2007)",                     #8
                "Lodgepole Pine (McCarter and Long 1986)",           #9
                "Spruce/Fir (Weiskittel and Woodall 2023)",         #10
                "Red Spruce (Weiskittel and Woodall 2023)",         #11
                "Balsam Fir (Weiskittel and Woodall 2023)",         #12
                "Redwood/Douglas-fir (Ritchie and Berrill 2022)",   #13
                "Douglas-fir/Redwood (Ritchie and Berrill 2022)",   #14
                "loblolly pine (Williams 1994)",                    #15
                "NW mixed-conifer: Kimsey Jr. et al. (2019)")       #16

if (input$ineq == 16) { 
SP_REF <- paste (SP_REF, switch(as.numeric(input$IFCsp),
                                "INW-DF", 
                                "INW-GF",
                                "INW-LP",
                                "INW-PP",
                                "INW-WL",
                                "PNW-DF Mix",
                                "PNW-HEMFIR"), sep = "/")
  }

UNIT <- ifelse(input$use.metric, "Metric", "English")

REINEKE <- switch(as.numeric(input$ineq),
                  input$reineke.term,                    #1
                    1.6000,                              #2
                    1.7721,                              #3
                    1.66113,                             #4
                    1.7721,                              #5
                    1.600,                               #6
                    1.605,                               #7
                    1.500,                               #8
                    1.600,                               #9
                    1.605,                               #10
                    1.605,                               #11
                    1.605,                               #12
                    1.605,                               #13
                    1.605,                               #14
                    1.5053,                              #15
                    IFCslope(as.numeric(input$IFCsp)))   #16


if(!as.logical(input$use.metric)){ # English Units
    MAX_SDI <- switch(as.numeric(input$ineq),
                      ifelse(as.numeric(input$max.sdi) <= 1000 && as.numeric(input$max.sdi) >= 300, input$max.sdi, 400),  #1
                      450,                                                   #2
                      400,                                                   #3
                      410,                                                   #4
                      365,                                                   #5
                      ifelse(as.numeric(input$max.sdi) <= 600 && as.numeric(input$max.sdi) >= 450, input$max.sdi, 550 ),   #6
                      600,                                                   #7
                      800,                                                   #8
                      700,                                                   #9
                      ifelse(as.numeric(input$max.sdi) <= 564 && as.numeric(input$max.sdi) >= 527, input$max.sdi, 527 ),   #10
                      ifelse(as.numeric(input$max.sdi) <= 608 && as.numeric(input$max.sdi) >= 547, input$max.sdi, 547 ),   #11
                      ifelse(as.numeric(input$max.sdi) <= 669 && as.numeric(input$max.sdi) >= 502, input$max.sdi, 502 ),   #12
                      ifelse(as.numeric(input$max.sdi) <= 1000 && as.numeric(input$max.sdi) >= 700, input$max.sdi, 900),   #13
                      ifelse(as.numeric(input$max.sdi) <= 700 && as.numeric(input$max.sdi) >= 500, input$max.sdi, 700),    #14
                      400,                                                   #15
                      input$max.sdi)                                                           #16
  } else{ # metric units
    MAX_SDI <- switch(as.numeric(ineq),
                      ifelse(as.numeric(input$max.sdi) <= 2470 && as.numeric(input$max.sdi) >= 741, input$max.sdi , 988),
                      1110,
                      988,
                      1013,
                      901,
                      ifelse(!(as.numeric(input$max.sdi) <= 1482 && as.numeric(input$max.sdi) >= 1112), 1359, input$max.sdi),
                      1482,
                      1977,
                      1730,
                      ifelse(as.numeric(input$max.sdi) <= 1394 && as.numeric(input$max.sdi) >= 1302, input$max.sdi, 1302),
                      ifelse(as.numeric(input$max.sdi) <= 1502 && as.numeric(input$max.sdi) >= 1352, input$max.sdi, 1352),
                      ifelse(as.numeric(input$max.sdi) <= 1653 && as.numeric(input$max.sdi) >= 1240, input$max.sdi, 1240),
                      ifelse(as.numeric(input$max.sdi) <= 2470 && as.numeric(input$max.sdi) >= 1730, input$max.sdi, 2223),
                      ifelse(as.numeric(input$max.sdi) <= 1730 && as.numeric(input$max.sdi) >= 1235, input$max.sdi, 1730),
                      988,
                      input$max.sdi)
    
  }

MGT_ZONE <-paste(if (input$ineq==1|input$ineq==06) input$mgt.zone else c(0.35,0.60), collapse=" ")  

```

* Species and Reference: `r SP_REF`
* Measured unit: `r UNIT`
* Maximum SDI: `r MAX_SDI`
* Reineke's term (slope): `r REINEKE`
* Management Zone: [`r MGT_ZONE`]


## Estimated Stand Attributes

```{r, Estimated-Stand-Attributes, echo=FALSE, liadfawarning=FALSE, warning=FALSE}

library("kableExtra")


TABLE_OUT <- t1()

 if(input$ineq == 3) {
   colnames(TABLE_OUT) <- c("TPA", "QMD", "BA", 
                            "Volume", "(SE)", "Top Height", "(SE)",
                            "Biomass", "(SE)", "Canopy Cover", "(SE)")
 } else if (input$ineq == 2){
   colnames(TABLE_OUT) <- c("TPA", "QMD", "BA", "Volume")  
 } else if (input$ineq %in% c(6, 7, 9)){
   colnames(TABLE_OUT) <- c("TPA", "QMD", "BA", "Volume", "Top Height")  
 } else {
   colnames(TABLE_OUT) <- c("TPA", "QMD", "BA")}
 if(input$use.metric == TRUE){
   colnames(TABLE_OUT)[1] <- "TPH"
 }

ftnote <-  cap_maker (ineq = input$ineq, use.metric = input$use.metric)
ftnote2 <-  cap_maker2 (ineq = input$ineq, use.metric = input$use.metric)
Capt <- "Stand Attribute Summary"

kbl(TABLE_OUT, longtable = T, booktabs = T, caption = Capt) %>%
  kable_styling(latex_options = c('hold_position')) %>%
  footnote(general = c(ftnote, ftnote2))

```


```{r, optional-chuck, eval = Note_option, echo=FALSE}
asis_output('## Note\n') # Header that is only shown if Note_option == TRUE
asis_output(paste("*", input$comments)) # Other stuff that is only executed if Note_option == TRUE
```


```{r SDMD-plot, fig.height=9, warning=FALSE, echo=FALSE, message=FALSE}
p1()
```







